#line 2 "read_input.c"

#line 4 "read_input.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[330] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   36,   36,   34,   34,   40,   35,   35,   38,
       33,   32,   35,   35,   35,   35,    8,    9,   37,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   10,
       31,   35,   35,   33,   32,   34,   34,   33,   32,    0,
       33,    0,    0,    2,    0,    0,    1,    8,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       10,   31,   36,   36,   33,   34,   34,   33,    0,    0,
        2,    0,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   26,    0,    0,    0,    0,
        0,   11,    0,    0,    0,    0,    0,    0,   18,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   26,    0,
        0,    0,    0,   27,    0,    0,   11,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   18,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   27,    0,    0,    0,    0,    0,    0,    0,    0,
       13,    0,    0,    0,   12,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,   22,    0,    0,
        0,    0,    0,    5,    0,    0,    0,    0,    0,    0,
       27,    0,   28,    0,    0,   14,   13,    0,   12,    0,
        0,   16,    0,    0,    0,   20,    0,    0,   22,    0,
        0,    0,    0,    0,    3,    0,    0,    0,    0,    0,
        0,    0,   13,    0,   12,    0,    0,   16,    0,    0,
       19,    0,   22,    0,    0,    0,    0,    0,    0,    4,
        0,    0,   17,   13,   12,    0,    0,    0,    0,   23,

        6,    0,    7,    4,   30,    0,   17,    0,    0,    0,
       24,    7,   30,    0,    0,    0,    0,    0,    0,    0,
        0,   29,    0,   15,   25,    0,   21,   25,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    7,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,    1,
       10,    1,    1,    1,   11,   12,    1,    1,   13,    1,
        1,   14,   15,    1,    1,   16,   17,   18,   19,    1,
        1,   20,   21,   22,    1,    1,    1,   23,    1,    1,
        1,    1,    1,    1,    1,    1,   24,   25,   26,   27,

       28,    1,   29,   30,   31,    1,   32,   33,   34,   35,
       36,   37,    1,   38,   39,   40,    1,   41,   42,   43,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[335] =
    {   0,
        0,    4,    8,   25,   33,   41,   49,   53,   67,  100,
       58,   72,  133,  685,   79,   94,  160,  684,  112,  120,
      138,  165,   86,  128,  177,  185,  688,  691,   17,  691,
      691,  691,  659,   21,  662,   37,  676,  675,  691,  648,
      189,  647,  649,  643,  655,  643,  222,  642,  637,  641,
      642,  630,  637,  249,  636,  631,  641,  636,  627,  657,
      656,    0,  106,    0,    0,    0,  148,    0,    0,  152,
      691,   30,  156,  116,  629,  173,  193,  654,  653,  630,
      202,  628,  622,  634,  630,  625,  616,  611,  622,    0,
      613,  617,  618,  606,  621,  607,    9,  615,  608,  613,

        0,  604,  614,  609,  600,  612,   24,  598,  606,  612,
      626,  625,    0,  196,    0,    0,  206,    0,  602,  606,
      201,  604,  210,  590,  610,  593,  227,  596,  586,  604,
      596,  580,  587,  586,  584,  579,  596,  576,  588,  591,
      579,  575,  577,  581,  589,  214,  589,  568,  231,  253,
      567,  217,  595,  568,  254,  261,  564,  266,  218,  589,
      574,  573,  275,  560,  559,  224,  564,  569,  230,  573,
      567,  285,    6,   58,   70,  276,  245,  579,  280,  293,
      298,  306,  311,  565,  319,  324,  279,  579,  332,  554,
      333,  342,  562,  337,  569,  577,  573,  562,  557,  569,

      545,   91,  292,  350,  336,  547,  351,  354,  360,   98,
      364,  136,  372,  140,  376,  163,  543,  387,  230,  377,
      264,  560,  355,  397,  398,  405,  303,  388,  316,  541,
      413,  416,  555,  691,  564,  538,  535,  523,  509,  540,
      515,  417,  481,  456,  420,  467,  424,  381,  428,  432,
      419,  416,  441,  437,  449,  440,  453,  457,  434,  458,
      404,  466,  404,  392,  691,  407,  378,  467,  372,  374,
      287,  313,  466,  305,  472,  285,  287,  260,  251,  480,
      243,  233,  216,  189,  176,  162,  179,  481,  484,  373,
      152,  151,  491,  491,  495,  143,  104,   94,   85,  691,

      691,  503,  504,  507,  508,  512,  513,  516,   61,  517,
      691,  521,  526,  527,  530,  531,  534,   45,  538,  542,
      543,   40,  551,   23,  552,  555,    9,  559,  691,  564,
      567,  570,    0,  573
    } ;

static yyconst flex_int16_t yy_def[335] =
    {   0,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,   13,  330,  330,  330,   17,  330,  330,
      330,  330,  331,  331,  332,  332,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  333,  333,  333,  333,  334,  334,  334,  334,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,   47,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

       54,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  333,  333,  333,  334,  334,  334,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,    0,  329,
      329,  329,  329,  329
    } ;

static yyconst flex_int16_t yy_nxt[735] =
    {   0,
      113,   29,   30,   29,   31,   29,   30,   29,   32,   29,
       30,   29,   31,  174,  175,   33,   37,  327,   70,   34,
       70,   71,   73,   35,   73,   36,   29,   30,   29,   32,
       74,  324,  132,   37,   29,   30,   29,   31,   76,  133,
       76,   38,   29,   30,   29,   32,   77,  138,  322,   38,
       29,   39,   29,   31,   29,   39,   29,   32,  119,   29,
       39,   29,   31,   40,  120,  139,  202,   40,   41,   39,
       41,   31,   46,   29,   39,   29,   32,  174,  175,   42,
       29,   39,   29,   31,  325,  203,   46,   29,   30,   63,
       64,  318,   43,   53,   44,   29,   39,   29,   32,  202,

       45,   41,   39,   41,   32,  211,  212,   70,   53,  114,
      115,  311,   42,   29,   30,   29,   31,  121,  203,  121,
       60,   29,   30,   29,   32,   43,  310,   44,   60,   29,
       30,   63,   65,   45,   47,   39,   47,   31,  309,   29,
       30,   29,   31,  211,  212,   48,   61,  215,  216,  117,
       49,  117,  118,   70,   50,   70,   71,   73,   51,   73,
       52,   54,   39,   54,   31,   74,   29,   30,   29,   32,
      215,  216,   55,   61,   76,  308,   76,   56,   67,   30,
       67,   68,   77,  306,   57,   58,   67,   30,   67,   69,
       81,  305,   81,   71,  123,  301,  123,   70,   59,  114,

      115,  300,  121,   81,  121,   81,   71,  117,  299,  117,
      118,  123,  298,  123,   82,  169,   83,  169,  177,  187,
      177,  187,   84,   90,  283,   90,   71,   82,  149,   83,
      149,  169,  149,  169,  149,   84,  150,  220,  221,   91,
      150,  283,  195,   92,  196,  197,  177,   93,  177,   94,
      101,  281,  101,   71,  172,  180,  172,  180,  173,  173,
      174,  175,  182,  181,  182,  297,  102,  185,  278,  185,
      183,  220,  221,  103,  104,  186,  191,  204,  191,  204,
      187,  207,  187,  207,  192,  205,  172,  105,  172,  208,
      173,  173,  174,  175,  180,  278,  180,  240,  240,  209,

      241,  209,  181,  210,  210,  211,  212,  182,  296,  182,
      228,  229,  213,  275,  213,  183,  214,  214,  215,  216,
      185,  273,  185,  228,  229,  218,  293,  218,  186,  219,
      219,  220,  221,  223,  191,  223,  191,  242,  231,  242,
      231,  224,  192,  226,  243,  226,  232,  227,  227,  228,
      229,  204,  207,  204,  207,  245,  223,  245,  223,  205,
      208,  209,  246,  209,  224,  210,  210,  211,  212,  210,
      210,  211,  247,  213,  304,  213,  304,  214,  214,  215,
      216,  214,  214,  215,  249,  252,  272,  272,  218,  273,
      218,  248,  219,  219,  220,  221,  259,  292,  255,  257,

      255,  257,  291,  250,  253,  256,  226,  258,  226,  288,
      227,  227,  228,  229,  231,  260,  231,  262,  242,  262,
      242,  245,  232,  245,  252,  243,  287,  286,  246,  210,
      210,  211,  247,  214,  214,  215,  249,  274,  274,  285,
      275,  263,  259,  253,  284,  264,  277,  277,  256,  278,
      255,  248,  255,  279,  257,  250,  257,  256,  280,  276,
      280,  260,  258,  282,  282,  281,  283,  262,  289,  262,
      289,  210,  210,  211,  294,  246,  290,  214,  214,  215,
      295,  280,  302,  280,  302,  289,  271,  289,  281,  243,
      303,  263,  307,  290,  307,  264,  210,  210,  211,  294,

      214,  214,  215,  295,  302,  312,  302,  312,  304,  313,
      304,  313,  303,  314,  307,  314,  307,  316,  319,  316,
      319,  315,  312,  241,  312,  317,  320,  313,  314,  313,
      314,  321,  316,  321,  316,  323,  315,  323,  322,  319,
      317,  319,  324,  326,  321,  326,  321,  320,  241,  270,
      327,  322,  323,  328,  323,  328,  326,  269,  326,  324,
      328,  268,  328,  327,   28,   28,   28,   62,   62,   62,
       66,   66,   66,  116,  116,  267,  266,  265,  261,  254,
      251,  244,  239,  238,  237,  236,  235,  234,  233,  230,
      225,  222,  217,  206,  201,  200,  199,  198,  194,  193,

      190,  189,  188,  184,  179,  178,  176,  171,  170,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  148,  147,  146,
      145,  144,  143,  112,  111,  142,  141,  140,  137,  110,
      109,  108,  107,  136,  135,  134,  131,  130,   99,   98,
       97,   96,  129,  128,  127,  126,  125,   88,   87,   86,
      124,   79,   78,  122,  112,  111,  110,  109,  108,  107,
      106,  100,   99,   98,   97,   96,   95,   89,   88,   87,
       86,   85,   80,   79,   78,   75,   72,  329,   32,   32,
       27,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329
    } ;

static yyconst flex_int16_t yy_chk[735] =
    {   0,
      333,    1,    1,    1,    1,    2,    2,    2,    2,    3,
        3,    3,    3,  173,  173,    2,    3,  327,   29,    2,
       29,   29,   34,    2,   34,    2,    4,    4,    4,    4,
       34,  324,   97,    4,    5,    5,    5,    5,   36,   97,
       36,    5,    6,    6,    6,    6,   36,  107,  322,    6,
        7,    7,    7,    7,    8,    8,    8,    8,   72,   11,
       11,   11,   11,    7,   72,  107,  174,    8,    9,    9,
        9,    9,   11,   12,   12,   12,   12,  175,  175,    9,
       15,   15,   15,   15,  318,  174,   12,   23,   23,   23,
       23,  309,    9,   15,    9,   16,   16,   16,   16,  202,

        9,   10,   10,   10,   10,  210,  210,   63,   16,   63,
       63,  299,   10,   19,   19,   19,   19,   74,  202,   74,
       19,   20,   20,   20,   20,   10,  298,   10,   20,   24,
       24,   24,   24,   10,   13,   13,   13,   13,  297,   21,
       21,   21,   21,  212,  212,   13,   21,  214,  214,   67,
       13,   67,   67,   70,   13,   70,   70,   73,   13,   73,
       13,   17,   17,   17,   17,   73,   22,   22,   22,   22,
      216,  216,   17,   22,   76,  296,   76,   17,   25,   25,
       25,   25,   76,  292,   17,   17,   26,   26,   26,   26,
       41,  291,   41,   41,   77,  287,   77,  114,   17,  114,

      114,  286,  121,   81,  121,   81,   81,  117,  285,  117,
      117,  123,  284,  123,   41,  146,   41,  146,  152,  159,
      152,  159,   41,   47,  283,   47,   47,   81,  127,   81,
      127,  169,  149,  169,  149,   81,  127,  219,  219,   47,
      149,  282,  166,   47,  166,  166,  177,   47,  177,   47,
       54,  281,   54,   54,  150,  155,  150,  155,  150,  150,
      150,  150,  156,  155,  156,  279,   54,  158,  278,  158,
      156,  221,  221,   54,   54,  158,  163,  176,  163,  176,
      187,  179,  187,  179,  163,  176,  172,   54,  172,  179,
      172,  172,  172,  172,  180,  277,  180,  203,  203,  181,

      203,  181,  180,  181,  181,  181,  181,  182,  276,  182,
      227,  227,  183,  274,  183,  182,  183,  183,  183,  183,
      185,  272,  185,  229,  229,  186,  271,  186,  185,  186,
      186,  186,  186,  189,  191,  189,  191,  205,  194,  205,
      194,  189,  191,  192,  205,  192,  194,  192,  192,  192,
      192,  204,  207,  204,  207,  208,  223,  208,  223,  204,
      207,  209,  208,  209,  223,  209,  209,  209,  209,  211,
      211,  211,  211,  213,  290,  213,  290,  213,  213,  213,
      213,  215,  215,  215,  215,  220,  248,  248,  218,  248,
      218,  211,  218,  218,  218,  218,  228,  270,  224,  225,

      224,  225,  269,  215,  220,  224,  226,  225,  226,  267,
      226,  226,  226,  226,  231,  228,  231,  232,  242,  232,
      242,  245,  231,  245,  252,  242,  266,  264,  245,  247,
      247,  247,  247,  249,  249,  249,  249,  250,  250,  263,
      250,  232,  259,  252,  261,  232,  253,  253,  256,  253,
      255,  247,  255,  254,  257,  249,  257,  255,  258,  251,
      258,  259,  257,  260,  260,  258,  260,  262,  268,  262,
      268,  273,  273,  273,  273,  246,  268,  275,  275,  275,
      275,  280,  288,  280,  288,  289,  244,  289,  280,  243,
      288,  262,  293,  289,  293,  262,  294,  294,  294,  294,

      295,  295,  295,  295,  302,  303,  302,  303,  304,  305,
      304,  305,  302,  306,  307,  306,  307,  308,  310,  308,
      310,  306,  312,  241,  312,  308,  310,  313,  314,  313,
      314,  315,  316,  315,  316,  317,  314,  317,  315,  319,
      316,  319,  317,  320,  321,  320,  321,  319,  240,  239,
      320,  321,  323,  325,  323,  325,  326,  238,  326,  323,
      328,  237,  328,  326,  330,  330,  330,  331,  331,  331,
      332,  332,  332,  334,  334,  236,  235,  233,  230,  222,
      217,  206,  201,  200,  199,  198,  197,  196,  195,  193,
      190,  188,  184,  178,  171,  170,  168,  167,  165,  164,

      162,  161,  160,  157,  154,  153,  151,  148,  147,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  126,  125,  124,
      122,  120,  119,  112,  111,  110,  109,  108,  106,  105,
      104,  103,  102,  100,   99,   98,   96,   95,   94,   93,
       92,   91,   89,   88,   87,   86,   85,   84,   83,   82,
       80,   79,   78,   75,   61,   60,   59,   58,   57,   56,
       55,   53,   52,   51,   50,   49,   48,   46,   45,   44,
       43,   42,   40,   38,   37,   35,   33,   27,   18,   14,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,

      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329,  329,  329,  329,  329,  329,  329,
      329,  329,  329,  329
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "read_input.l"
#line 15 "read_input.l"
#include<stdlib.h>
#include<stdio.h>
#include<string.h>
#include"cudaglobal.h"
#include"global.h"
#include"read_input.h"

int line_of_file=1;
int comment_caller;
int a,b;
float c;
char name[100];
  
  
// Overrelaxation parameters
int orxmaxit;
int orxcheckinterval;
double orxeps;  
int orxflag = 0;


// Sim. ann. parameters
SAPARAM_LIST saparam;
int saflag = 0;
//saparam.checkint = 1;

// Therm. parameters
THERMPARAM_LIST thermparam;
int thermflag = 0;
//thermparam.checkint = 1;

int randseed;
  
//benchmark flag
int benchmarkflag = 0;
int benchmarksweeps = 0;

  /* Name of the parsing routine */
#define YY_DECL         int parse_input()
#define YY_NO_UNPUT












#line 783 "read_input.c"

#define INITIAL 0
#define TT 1
#define LL 2
#define INITORX 3
#define OVERRELAX 4
#define INITSA 5
#define SIMANN 6
#define INITTHERM 7
#define THERM 8
#define RND 9
#define BENCH 10
#define ERROR 11
#define COMMENT 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 79 "read_input.l"


#line 988 "read_input.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 330 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 329 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 81 "read_input.l"
BEGIN(TT);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "read_input.l"
BEGIN(LL);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "read_input.l"
BEGIN(INITORX);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "read_input.l"
BEGIN(RND);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "read_input.l"
BEGIN(INITSA);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "read_input.l"
BEGIN(INITTHERM);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "read_input.l"
BEGIN(BENCH);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "read_input.l"
{
  T = atoi(yytext);
  printf("T = %s\n", yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "read_input.l"
{
  L = atoi(yytext);
  printf("L = %s\n", yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "read_input.l"
{
  randseed = atoi(yytext);
  printf("Random Seed = %s\n", yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 105 "read_input.l"
{
 printf("Found sim. annealing block in line %d\n", line_of_file); 
 BEGIN(SIMANN);
 }
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 110 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    saparam.Tmin = c;
    printf(" SA Tmin set to %e in line %d\n", c, line_of_file);
  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    saparam.Tmax = c;
    printf(" SA Tmax set to %e in line %d\n", c, line_of_file);
  } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    saparam.N = a;
    printf(" SA steps set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 125 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    saparam.checkint = a;
    printf(" SA check interval set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 130 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    saparam.expo = c;
    printf(" SA temperature expo set to %e in line %d\n", c, line_of_file);
  }  
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "read_input.l"
{
  saflag=1;
  printf("End sim. annealing block in line %d\n\n", line_of_file);
  BEGIN(0);
  }
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 147 "read_input.l"
{
 printf("Found thermalization block in line %d\n", line_of_file); 
 BEGIN(THERM);
 }
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 152 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    thermparam.Nsweep = a;
    printf(" Nsweep set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 157 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    thermparam.Nsave = a;
    printf(" Nsave set to %d line %d\n", a, line_of_file);
  }  
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 162 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    thermparam.checkint = a;
    printf(" Therm. check interval set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 167 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    thermparam.beta = c;
    printf(" beta set to %e in line %d\n", c, line_of_file);
  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 172 "read_input.l"
{
    thermparam.startcond = 1;
    printf(" using hot start in line %d\n", line_of_file);
  }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 176 "read_input.l"
{
    thermparam.startcond = 0;
    printf(" using cold start in line %d\n", line_of_file);
  }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 180 "read_input.l"
{
  thermflag=1;
  printf("End thermalization block in line %d\n\n", line_of_file);
  BEGIN(0);
  }
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 189 "read_input.l"
{
 printf("Found overrelaxation block in line %d\n", line_of_file); 
 BEGIN(OVERRELAX);
 }
	YY_BREAK

case 27:
YY_RULE_SETUP
#line 194 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %f", name, &c);
    orxeps = c;
    printf(" Overrelaxation dAdA epsilon set to %e in line %d\n", c, line_of_file);
  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 199 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    orxmaxit = a;
    printf(" Overrelaxation max iterations set to %d line %d\n", a, line_of_file);
  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 204 "read_input.l"
{
    sscanf(yytext, " %[2a-zA-Z] = %d", name, &a);
    orxcheckinterval = a;
    printf(" Overrelaxation check interval set to %d line %d\n", a, line_of_file);
  }  
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 209 "read_input.l"
{
  orxflag=1;
  printf("End overrelaxation block in line %d\n\n", line_of_file);
  BEGIN(0);
  }
	YY_BREAK

case 31:
YY_RULE_SETUP
#line 218 "read_input.l"
{
  benchmarkflag = 1;
  benchmarksweeps = atoi(yytext);;
  printf(" Benchmark sweeps set to %d line %d\n", benchmarksweeps);
  printf(" Doing benchmark\n");
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 229 "read_input.l"
{
   comment_caller = YY_START;   
   BEGIN(COMMENT);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 233 "read_input.l"
{
   comment_caller = YY_START;
   BEGIN(COMMENT);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 237 "read_input.l"
{
  BEGIN(comment_caller);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 241 "read_input.l"
{
  BEGIN(ERROR);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 244 "read_input.l"
{
  printf("Parsing error in line %d\nAborting...!\n", line_of_file);
  printf("%s\n",yytext);
  exit(1);
}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 251 "read_input.l"
{
  line_of_file++;
}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 254 "read_input.l"
{
  line_of_file++;
  BEGIN(0);
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 263 "read_input.l"
ECHO;
	YY_BREAK
#line 1379 "read_input.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TT):
case YY_STATE_EOF(LL):
case YY_STATE_EOF(INITORX):
case YY_STATE_EOF(OVERRELAX):
case YY_STATE_EOF(INITSA):
case YY_STATE_EOF(SIMANN):
case YY_STATE_EOF(INITTHERM):
case YY_STATE_EOF(THERM):
case YY_STATE_EOF(RND):
case YY_STATE_EOF(BENCH):
case YY_STATE_EOF(ERROR):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 330 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 330 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 329);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 263 "read_input.l"




/*
 *  Dummy (but not dumb) routine - well, function
 */

int yywrap()
{
  return(1);
}


int read_input(char * conf_file){

  if ((yyin = fopen(conf_file, "rt")) == NULL){
    return(2);
  }
  
  yyout = fopen("/dev/null", "w");
  
  parse_input();  
 
  
  LX=L;
  LY=L;
  LZ=L;
  VOLUME=LX*LY*LZ*T;
   
  fclose(yyout);
  fclose(yyin);
  return(0);
}



